return {
  {
    'nvim-treesitter/nvim-treesitter',
    dependencies = {
      'nvim-treesitter/nvim-treesitter-textobjects',
      { 'JoosepAlviste/nvim-ts-context-commentstring', opts = {} },
    },
    build = ':TSUpdate',
    event = { 'BufRead', 'BufNewFile' },
    opts = {
      sync_install = false,
      ensure_installed = {
        'bash',
        'c_sharp',
        'comment',
        'css',
        'diff',
        'dockerfile',
        'fsharp',
        'go',
        'gomod',
        'gosum',
        'gowork',
        'graphql',
        'hcl',
        'helm',
        'html',
        'http',
        'ini',
        'jq',
        'json',
        'json',
        'json5',
        'jsonc',
        'latex',
        'lua',
        'luadoc',
        'luap',
        'make',
        'markdown',
        'markdown_inline',
        'ninja',
        'python',
        'query',
        'regex',
        'ron',
        'rst',
        'rust',
        'scss',
        'sql',
        'ssh_config',
        'templ',
        'terraform',
        'toml',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
      },
      highlight = { enable = true },
      indent = { enable = true },
      textobjects = {
        move = {
          enable = true,
          set_jumps = true,
        },
        select = {
          enable = true,
          lookahead = false,
          keymaps = {
            ['aa'] = '@parameter.outer',
            ['ia'] = '@parameter.inner',
            ['af'] = '@function.outer',
            ['if'] = '@function.inner',
            ['ac'] = '@class.outer',
            ['ic'] = '@class.inner',
          },
        },
        swap = {
          enable = true,
          swap_next = {
            ['g>'] = '@parameter.inner',
          },
          swap_previous = {
            ['g<'] = '@parameter.inner',
          },
        },
      },
    },
    config = function(_, opts) require('nvim-treesitter.configs').setup(opts) end,
  },
}
